# Generated by Django 5.0.4 on 2024-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamIdentifier', '0002_remove_spamreport_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
