# Generated by Django 5.0.4 on 2024-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamIdentifier', '0003_registereduser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
