# Generated by Django 5.0.4 on 2024-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamIdentifier', '0007_remove_registereduser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
