# Generated by Django 5.0.4 on 2024-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamIdentifier', '0008_rename_username_registereduser_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spamreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spamreport',
            name='reported_by',
        ),
    ]
